[workspace]
members = ["proc_macro_test"]

[package]
name = "test_app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.80"
rand = "0.8.5"

[dev-dependencies]
cargo_pup_lint_config = { path = "../cargo_pup_lint_config" }
