[package]
name = "cargo_pup_common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tempfile.workspace = true
regex = "1.11.1"